/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "CURT_GPIO/CURT_GPIO_headers/GPIO_INTERFACE.h"
#include "CURT_RCC/CURT_RCC_headers/RCC_interface.h"


int main(void){

	RCC_voidInitSysClock();


	GPIO_enablePortClock(GPIO_PortA);
	GPIO_setupPinMode(GPIO_PortA,2,INPUT_PULLUP_PULLDOWN);
	GPIO_setupPinMode(GPIO_PortA,3,INPUT_PULLUP_PULLDOWN);
	GPIO_setupPinMode(GPIO_PortA,5,INPUT_PULLUP_PULLDOWN);
	GPIO_setupPinMode(GPIO_PortA,13,INPUT_PULLUP_PULLDOWN);

	GPIO_setPinValue(GPIO_PortA,2,1);
	GPIO_setPinValue(GPIO_PortA,3,1);
	GPIO_setPinValue(GPIO_PortA,5,1);
	GPIO_setPinValue(GPIO_PortA,13,1);

	GPIO_setupPortMode(GPIO_PortB,OUTPUT_SPEED_10MHZ_AFPP);
	GPIO_setupPortMode(GPIO_PortB,OUTPUT_SPEED_10MHZ_AFOD);
	GPIO_writePort(GPIO_PortB,0xFAB2);
	GPIO_writePort(GPIO_PortB,0);

	GPIO_togglePinValue(GPIO_PortB,PIN0);
	GPIO_togglePinValue(GPIO_PortB,PIN0);

	GPIO_togglePinValue(GPIO_PortB,PIN3);

	GPIO_togglePinValue(GPIO_PortB,PIN5);
	GPIO_togglePinValue(GPIO_PortB,PIN5);

	GPIO_togglePinValue(GPIO_PortB,PIN15);

	GPIO_togglePinValue(GPIO_PortB,PIN12);
	GPIO_togglePinValue(GPIO_PortB,PIN12);
	GPIO_lockPort(GPIO_PortB);
	GPIO_togglePinValue(GPIO_PortB,PIN12);
	for(;;){

	}
}
