
name: Generate doxygen docs
on:
  push:
    branches:
      - "Hazem_Montasser"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Doxygen"
        run: |
          sudo apt-get install -y doxygen
          doxygen Doxyfile


