
name: Generate doxygen docs
on:
  push:
    branches:
      - "Hazem_Montasser"    
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'BluePill Drivers'
          additional-packages: font-fira-code
